export const CONSROCIO2 = [
    { "Codigo": "8X2", "Nombre": "PIJA P/TABLAROCA 8X2 C/100", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 48, "Precio Credito": 52, "Cantidad": "400", "Dañados": 0 },
    { "Codigo": "JGO-CA56", "Nombre": "JUEGO DE HERRAMIENTAS CASERO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 305, "Precio Credito": 320, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "17538", "Nombre": "SILICON BARRAS TRUPER", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 55, "Precio Credito": 60, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "FKF-30A", "Nombre": "FUSIBLE GAMA ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 10, "Precio Credito": 15, "Cantidad": "12", "Dañados": 0 },
    { "Codigo": "PAFDO-S", "Nombre": "PLACA DOBLE CAJA VOLTECH ESTANDAR", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 52, "Precio Credito": 55, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "22851", "Nombre": "REMACHADORA DE 254MM PRETUL ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 15, "Precio Credito": 20, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "20055", "Nombre": "ASPERSOR PLASTICO C/ESTACA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 60, "Precio Credito": 65, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "18298", "Nombre": "SIERRA CIRCULAR 7 1/4¨ TRUPER", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 210, "Precio Credito": 215, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "NH-3", "Nombre": "NIVEL DE HILO 3´´ TRUPER", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 22, "Precio Credito": 25, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "46532", "Nombre": "PORTA LAMPARA P/REFLECTOR", "Precio Compra": 6.5, "Precio Mayoreo": 1.35, "Precio Unitario": 8, "Precio Credito": 10, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "44360", "Nombre": "TAQUETE DE EXPANSIÓN 1/4´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 17, "Precio Credito": 20, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "14386", "Nombre": "ESCUADRA P/CANTERO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 85, "Precio Credito": 90, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "A00687", "Nombre": "BROCHA PERFEL 500-4´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "16979", "Nombre": "REPUESTO P/EXACTO PROFESIONAL", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 40, "Precio Credito": 45, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "11579", "Nombre": "DISCO DE DIAMANTE 7´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 380, "Precio Credito": 385, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "2555", "Nombre": "DISCO DE DIAMANTE P/CORTE USO GENERAL", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 91, "Precio Credito": 95, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "17356", "Nombre": "PINZA PELA CABLE TRUPER", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 109, "Precio Credito": 120, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "16566", "Nombre": "CARBON P/SIERRA CIRCULAR ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 62, "Precio Credito": 65, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "1996-09-01", "Nombre": "SEPARADOR DE 10MM", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 90, "Precio Credito": 100, "Cantidad": "100", "Dañados": 0 },
    { "Codigo": "49618", "Nombre": "COLADERA DE ABS C/SALIDA LATERAL", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 90, "Precio Credito": 100, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "OMME", "Nombre": "EXTENSION 6 M OMME", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "OMME-01", "Nombre": "EXTENSION 8 M OMME", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "45009", "Nombre": "TAPA CUADRADA P/CAJA VOLTECH", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 8, "Precio Credito": 10, "Cantidad": "35", "Dañados": 0 },
    { "Codigo": "SEG-00", "Nombre": "SEGURO P/LAVABO GALVANIZADO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 10, "Precio Credito": 15, "Cantidad": "24", "Dañados": 0 },
    { "Codigo": "2021-04-03", "Nombre": "COPLE GALVANIZADO 3/4", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 20, "Precio Credito": 25, "Cantidad": "42", "Dañados": 0 },
    { "Codigo": "2021-02-01", "Nombre": "COPLE GALVANIZADO 1/2", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 15, "Precio Credito": 20, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "ESP", "Nombre": "ESPATULA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 8, "Precio Credito": 20, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "185-17", "Nombre": "BOMBA ADIR 1/2HP ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 590, "Precio Credito": 600, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "COLOR", "Nombre": "COLOR P/CEMENTO AMARILLO PRESA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "LMG-04", "Nombre": "GAS BUTANO EN AEROSOL", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 55, "Precio Credito": 60, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "TAP00", "Nombre": "TAPA CUADRADA P/CAJA 9X9 VOLTECK", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 13, "Precio Credito": 15, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "PUL-045", "Nombre": "COPLE GALVANIZADO DE 4´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 8, "Precio Credito": 10, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "2026-3", "Nombre": "BASE P/MEDIDOR UISA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 110, "Precio Credito": 120, "Cantidad": "6", "Dañados": 0 },
    { "Codigo": "IIU2030", "Nombre": "INTERRUPTOR DE 2POLOS IGESA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 150, "Precio Credito": 160, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "00D2", "Nombre": "CENTRO DE CARGA SQUARE", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 225, "Precio Credito": 250, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "00D1", "Nombre": "CENTRO DE CARGA SQUARE", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 170, "Precio Credito": 180, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "CC01E", "Nombre": "CENTRO DE CARGA IGESA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "Q0045", "Nombre": "CENTRO DE CARGA SQUARE", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 260, "Precio Credito": 270, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "DURETAN", "Nombre": "SILICON DURETAN GRIS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 160, "Precio Credito": 170, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "N0.14", "Nombre": "CESPOL MULTIFORMAS P/FREGADERO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 65, "Precio Credito": 70, "Cantidad": "6", "Dañados": 0 },
    { "Codigo": "SKU-3100", "Nombre": "VALVULA DE LLENADO DE 3/4", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 170, "Precio Credito": 180, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "SKU-310046", "Nombre": "FLOTADOR NO.5", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 70, "Precio Credito": 80, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "MULTI", "Nombre": "MULTICONECTOR REFORZADO 1´´ A 3/4", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 135, "Precio Credito": 140, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "CONDUIT", "Nombre": "TUBO CONDUIT 3 M ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 170, "Precio Credito": 180, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "CONDULET", "Nombre": "TUBO CONDUIT 1.5 M", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 100, "Precio Credito": 110, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "FDLEX-99", "Nombre": "CONECTOR FLEXIBLE DE 1/2X 1/2 X 45 P/LAVABO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 8, "Precio Credito": 20, "Cantidad": "9", "Dañados": 0 },
    { "Codigo": "9772", "Nombre": "CESPOL P/LAVABO REGILLA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "7", "Dañados": 0 },
    { "Codigo": "CESP-01", "Nombre": "CESPOL P/FREGADERO MULTIFORMAS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 65, "Precio Credito": 70, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "ROO109", "Nombre": "RODILLO JUMBO PERFECT ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "6", "Dañados": 0 },
    { "Codigo": "9114", "Nombre": "HERRAJE P/SANITARIO AZTECA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "TIJERA-9", "Nombre": "TIJERA P/PODAR TRUPER ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 250, "Precio Credito": 260, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "SERRUCHO", "Nombre": "SERRUCHO P/PODAR DE 14´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 180, "Precio Credito": 190, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "18165", "Nombre": "SERRUCHO TRUPER 12´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 140, "Precio Credito": 150, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "14186", "Nombre": "PISTOLA P/PEGAMENTO TRUPER", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 160, "Precio Credito": 170, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "17550", "Nombre": "PISTOLA P/PEGAMENTO 17550 TRUPER", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 70, "Precio Credito": 80, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "025-6T", "Nombre": "BIRLOS P/LAMINA DE 20 CM DELGADA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 3, "Precio Credito": 6, "Cantidad": "100", "Dañados": 0 },
    { "Codigo": "S23", "Nombre": " EXTENSION VOLTECK 3 M OMME", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 30, "Precio Credito": 35, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "48046", "Nombre": "EXTENSION VOLTECK 10 M", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 145, "Precio Credito": 150, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "46334", "Nombre": "PORTA LAMPARA CONSENSOR", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 190, "Precio Credito": 200, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "339294", "Nombre": "SOPLETE PRECIMEX ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 115, "Precio Credito": 120, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "14P75M", "Nombre": "FLEXOMETRO 7.5M ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 175, "Precio Credito": 180, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "21053", "Nombre": "CUCHARA SOLDADA PRETUL 9´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "43558", "Nombre": "CERRADURA P/MUEBLES HERMEX", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 52, "Precio Credito": 60, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "16243", "Nombre": "JUEGO DE CUCHILLAS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 780, "Precio Credito": 800, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "PLASS", "Nombre": "PLASTILOKA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 25, "Precio Credito": 30, "Cantidad": "9", "Dañados": 0 },
    { "Codigo": "16-0209", "Nombre": "SILICON FORTE ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 40, "Precio Credito": 45, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "NI250-03", "Nombre": "FLEXOMETRO NICHOLSON 3 M", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 40, "Precio Credito": 45, "Cantidad": "12", "Dañados": 0 },
    { "Codigo": "50020", "Nombre": "FLEXOMETRO 5M BELLOTA ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 80, "Precio Credito": 90, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "EXTE", "Nombre": "EXTENCION 10M OMME", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 52, "Precio Credito": 60, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "A00658", "Nombre": "BROCHA PERFECT 5´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "A00689", "Nombre": "BROCHA PERFECT 6´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 55, "Precio Credito": 60, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "A00682", "Nombre": "BROCHA PERFECT 1´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 10, "Precio Credito": 15, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "3501-20", "Nombre": "TIJERA DE PODA ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 220, "Precio Credito": 230, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "21824", "Nombre": "PERICO LLAVE PRETUL 10´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 165, "Precio Credito": 170, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "27022", "Nombre": "CONECTOR RAPÍDO TIPO F HEMBRA PRETUL", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 20, "Precio Credito": 30, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "PAS-96", "Nombre": "PASADOR P/PUERTA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 60, "Precio Credito": 70, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "US-09", "Nombre": "EXTENCION USO RUDO AROLA 10 M", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 100, "Precio Credito": 110, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "INT ", "Nombre": "INTERRUPTOR TERMOMAGNETICO 1 POLO ISA VOLTECK", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 60, "Precio Credito": 70, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "21882", "Nombre": "LLAVE CONVINADA ESTANDAR 3/8´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 26, "Precio Credito": 30, "Cantidad": "24", "Dañados": 0 },
    { "Codigo": "61198", "Nombre": "DESARMADOR 4X4 BELLOTA PLANO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "T02026", "Nombre": "DESARMADOR DE CRUZ DOGO TUIS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "22603", "Nombre": "PINZA DE ELECTRICIDAD 7´´ PRETUL", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 110, "Precio Credito": 120, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "MANG", "Nombre": "MANGUERA P/GAS DE 5 MTS ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 135, "Precio Credito": 140, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "9888", "Nombre": "MANGUERA P/GAS DE 2 MTS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 85, "Precio Credito": 90, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "4100", "Nombre": "MANGUERA P/GAS DE 3 MTS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 100, "Precio Credito": 110, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "41ML", "Nombre": "MANGUERA P/GAS DE 1 MTS", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "REFOR ", "Nombre": "MANGUERA P/GAS DE 1 MTS NEGRA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "GARR", "Nombre": "GARRAFON DE 4 LTS ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 25, "Precio Credito": 30, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "SOMB", "Nombre": "SOMBRERO DE 4´´ GALVANIZADO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 25, "Precio Credito": 30, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "TUB-0100", "Nombre": "TUBO GALVANIZADO DE 6´´ ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 120, "Precio Credito": 130, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "4PUL", "Nombre": "TUBO GALVANIZADO DE 4´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "49255", "Nombre": "JUEGO DE ACCESORIOS P/BAÑO VOLTECK", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 325, "Precio Credito": 330, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "10MM2", "Nombre": "MANGUERA P/GAS REFORZADO DE 10 M", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 290, "Precio Credito": 300, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "F03203", "Nombre": "HERRAJE P/SANITARIO FAMA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 85, "Precio Credito": 90, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "FAMA", "Nombre": "HIDROTOMA DE 2´´ A 1/2 EDO-MEX", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 85, "Precio Credito": 90, "Cantidad": "12", "Dañados": 0 },
    { "Codigo": "AMS", "Nombre": "HIDROTOMA DE 1´´1/2 A 1/2 EDO-MEX", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 70, "Precio Credito": 80, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "LTJ", "Nombre": "HIDROTOMA DE 1´´1/2 A 3/4 EDO-MEX", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "1234", "Nombre": "HIDROTOMA DE 2´´1/2 A 3/4 EDO-MEX", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 90, "Precio Credito": 95, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "HIDRO-OR", "Nombre": "HIDROTOMA DE 3´´ A 1/2 EDO-MEX", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 95, "Precio Credito": 100, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "AMANCO", "Nombre": "HIDROTOMA DE 3´´A 1/2 AMANCO 03-61", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 85, "Precio Credito": 90, "Cantidad": "6", "Dañados": 0 },
    { "Codigo": "AMA-05", "Nombre": "HIDROTOMA AMANCO 3´´ A 3/4", "Precio Compra": 42.39, "Precio Mayoreo": 1.35, "Precio Unitario": 60, "Precio Credito": 65, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "1-2A1-2", "Nombre": "HIDROTOMA 1´´ 1/2 A 1/2", "Precio Compra": 52.13, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "PVC-010", "Nombre": "HIDROTOMA 2´´ 3/4 A 3/4 PVC", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "HOOO55", "Nombre": "CEPILLO DE ALAMBRE ", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 30, "Precio Credito": 35, "Cantidad": "7", "Dañados": 0 },
    { "Codigo": "10020", "Nombre": "GOMA ANYER DE 2´´ AL 1/4", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 5, "Precio Credito": 10, "Cantidad": "7", "Dañados": 0 },
    { "Codigo": "ABRAZ", "Nombre": "ABRAZADERA DE 4´´ 1/4", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 18, "Precio Credito": 20, "Cantidad": "10", "Dañados": 0 },
    { "Codigo": "2A3-4", "Nombre": "HIDROTOMA DE 2´´ A 3/4", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 85, "Precio Credito": 90, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "91-1-4", "Nombre": "ABRAZADERA DE 6´´ A 1/2", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 20, "Precio Credito": 25, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "2021-06-01", "Nombre": "ABRAZADERA 110MM TUBOPLAS SANITARIO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 45, "Precio Credito": 50, "Cantidad": "8", "Dañados": 0 },
    { "Codigo": "110MMR", "Nombre": "BANDA A-60 P/MOLINO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 100, "Precio Credito": 110, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "A-60", "Nombre": "BANDA A-56 P/MOLINO", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 95, "Precio Credito": 100, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "A-56", "Nombre": "BANDA P/MOLINO A-44", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 80, "Precio Credito": 85, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "A-44", "Nombre": "BANDA P/MOLINO A-36", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 75, "Precio Credito": 80, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "A-36", "Nombre": "HERRAJE BAYUSA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 55, "Precio Credito": 60, "Cantidad": "11", "Dañados": 0 },
    { "Codigo": "A746", "Nombre": "BANDA P/MOLINO A-91", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 245, "Precio Credito": 250, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "A-91", "Nombre": "BANDA P/MOLINO A-74", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 130, "Precio Credito": 135, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "A-74", "Nombre": "ABRAZADERA 2´´1/2", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 10, "Precio Credito": 15, "Cantidad": "48", "Dañados": 0 },
    { "Codigo": "1941-02-01", "Nombre": "ABRAZADERA DE 2´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 10, "Precio Credito": 45, "Cantidad": "4", "Dañados": 0 },
    { "Codigo": "AB-01", "Nombre": "ALAMBRE DE ACERO INOXIDABLE CALIBRE 20", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 100, "Precio Credito": 110, "Cantidad": "1KG", "Dañados": 0 },
    { "Codigo": "FIERRO", "Nombre": "PIG TAIL P/GAS 6X22 IUSA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 34, "Precio Credito": 36, "Cantidad": "14", "Dañados": 0 },
    { "Codigo": "ANLLER", "Nombre": "GOMA ANYER P/SANITARIO DE 4´´", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 15, "Precio Credito": 20, "Cantidad": "2", "Dañados": 0 },
    { "Codigo": "46934", "Nombre": "CONECTOR HERMETICO CURVO VOLTECK  3/4", "Precio Compra": 42.0, "Precio Mayoreo": 43.0, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "76", "Dañados": 0 },
    { "Codigo": "46933", "Nombre": "CONECTOR HERMETICO CURVO VOLTECK 1/2", "Precio Compra": 29.0, "Precio Mayoreo": 30.0, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "30", "Dañados": 0 },
    { "Codigo": "46979", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO T 1/2 VOLTECK", "Precio Compra": 45.0, "Precio Mayoreo": 46.0, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "70", "Dañados": 0 },
    { "Codigo": "46980", "Nombre": "CONECTOR HERMETICO CURVO 3/4 VOLTECK", "Precio Compra": 72.0, "Precio Mayoreo": 73.0, "Precio Unitario": 80, "Precio Credito": 85, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "46982", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO C 1/2 VOLTECK", "Precio Compra": 45.0, "Precio Mayoreo": 46.0, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "78", "Dañados": 0 },
    { "Codigo": "46983", "Nombre": "CAJA DE CONEXIÓN DE ALUMINIO TIPO C 3/4 VOLTECK", "Precio Compra": 72.0, "Precio Mayoreo": 73.0, "Precio Unitario": 80, "Precio Credito": 85, "Cantidad": "80", "Dañados": 0 },
    { "Codigo": "46930", "Nombre": "CONECTOR HERMETICO RECTO 1/2 VOLTECK", "Precio Compra": 22.0, "Precio Mayoreo": 23.0, "Precio Unitario": 30, "Precio Credito": 35, "Cantidad": "78", "Dañados": 0 },
    { "Codigo": "46931", "Nombre": "CONECTOR  HERMETICO RECTO 3/4 VOLTECK ", "Precio Compra": 27.0, "Precio Mayoreo": 28.0, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "90", "Dañados": 0 },
    { "Codigo": "46986", "Nombre": "CAJA DE CONEXON ALUMINIO TIPO FS 3/4 VOLTECK", "Precio Compra": 93.0, "Precio Mayoreo": 94.0, "Precio Unitario": 110, "Precio Credito": 120, "Cantidad": "65", "Dañados": 0 },
    { "Codigo": "46985", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO FS 1/2 VOLTECK", "Precio Compra": 93.0, "Precio Mayoreo": 94.0, "Precio Unitario": 110, "Precio Credito": 120, "Cantidad": "14", "Dañados": 0 },
    { "Codigo": "46977", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO LL 3/4 VOLTECK", "Precio Compra": 72.0, "Precio Mayoreo": 73.0, "Precio Unitario": 80, "Precio Credito": 85, "Cantidad": "95", "Dañados": 0 },
    { "Codigo": "46974", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO LR 3/4 VOLTECK", "Precio Compra": 72.0, "Precio Mayoreo": 73.0, "Precio Unitario": 80, "Precio Credito": 85, "Cantidad": "85", "Dañados": 0 },
    { "Codigo": "46971", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TPO LV 3/4 VOLTECK", "Precio Compra": 72.0, "Precio Mayoreo": 73.0, "Precio Unitario": 80, "Precio Credito": 85, "Cantidad": "50", "Dañados": 0 },
    { "Codigo": "46976", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO LL 1/2 VOLTECK", "Precio Compra": 45.0, "Precio Mayoreo": 46.0, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "105", "Dañados": 0 },
    { "Codigo": "46973", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO LR 1/2 VOLTECK", "Precio Compra": 45.0, "Precio Mayoreo": 46.0, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "65", "Dañados": 0 },
    { "Codigo": "46970", "Nombre": "CAJA DE CONEXIÓN ALUMINIO TIPO LV 1/2 VOLTECK", "Precio Compra": 45.0, "Precio Mayoreo": 46.0, "Precio Unitario": 50, "Precio Credito": 55, "Cantidad": "56", "Dañados": 0 },
    { "Codigo": "46953", "Nombre": "COPLE DE PARED DELGADO 3/4 VOLTECK ", "Precio Compra": 8.0, "Precio Mayoreo": 9.0, "Precio Unitario": 16, "Precio Credito": 20, "Cantidad": "50", "Dañados": 0 },
    { "Codigo": "46951", "Nombre": "CONECTOR  DE PARED DELGADO 3/4 VOLTECK", "Precio Compra": 11.5, "Precio Mayoreo": 13.0, "Precio Unitario": 20, "Precio Credito": 25, "Cantidad": "50", "Dañados": 0 },
    { "Codigo": "PHMOLD", "Nombre": "MOLDURA NO.#24 ECONOMICA", "Precio Compra": 23.0, "Precio Mayoreo": 31.0, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "20", "Dañados": 0 },
    { "Codigo": "MOLDURA-01", "Nombre": "MOLDURA NO.#15 ECONOMICA", "Precio Compra": 1.0, "Precio Mayoreo": 1.35, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "18", "Dañados": 0 },
    { "Codigo": "MOLDURA-02", "Nombre": "MOLDURA  NO.#3 ECONOMICA", "Precio Compra": 20.5, "Precio Mayoreo": 27.0, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "1", "Dañados": 0 },
    { "Codigo": "MOLDURA-03", "Nombre": "MOLDURA NO.#4 ECONOMICA", "Precio Compra": 20.57, "Precio Mayoreo": 27.0, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "5", "Dañados": 0 },
    { "Codigo": "MOLDURA-04", "Nombre": "MOLDURA NO.#6 ECONOMICA", "Precio Compra": 20.57, "Precio Mayoreo": 27.0, "Precio Unitario": 35, "Precio Credito": 40, "Cantidad": "3", "Dañados": 0 },
    { "Codigo": "MOLDREFOR-01", "Nombre": "MOLDURA NO.#3 REFORZADA", "Precio Compra": 40.5, "Precio Mayoreo": 54.0, "Precio Unitario": 60, "Precio Credito": 65, "Cantidad": "6", "Dañados": 0 },
    ];    